apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-receiver-deployment
  labels:
    app: thanos-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver
  template:
    metadata:
      labels:
        app: thanos-receiver
    spec:
      containers:
      - name: thanos-receiver
        image: {{ .Values.thanos.image }}
        ports:
        - containerPort: 10903
        - containerPort: 10904
        - containerPort: 10908
        command: ["thanos", "receive"]
        args: 
          - "--grpc-address=0.0.0.0:10903"
          - "--http-address=0.0.0.0:10904"
          - "--objstore.config={
            type: S3,
            config: { 
              bucket: {{ .Values.prometheusThanosStorageBucket.bucketName }},
              endpoint: {{ .Values.prometheusThanosStorageBucket.endpoint }},
              insecure: false,
              signature_version2: false,
              sse_config: {
                type: SSE-KMS,
                kms_key_id: {{ .Values.prometheusThanosStorageBucket.kmsKeyId }}
              }
            } 
          }"
          - "--tsdb.path=/var/lib/prometheus"
          - "--receive.local-endpoint=127.0.0.1:10903"
          - "--remote-write.address=0.0.0.0:10908"
          - "--log.level=debug"