apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store-deployment
  labels:
    app: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - name: thanos-store
        image: {{ .Values.thanos.image }}
        ports:
        - containerPort: 20091
        - containerPort: 20902
        command: ["thanos", "store"]
        args: 
          - "--grpc-address=0.0.0.0:20091"
          - "--http-address=0.0.0.0:20902"
          - "--data-dir=/tmp/thanos/store"
          - "--objstore.config={
            type: S3,
            config: { 
              bucket: {{ .Values.prometheusThanosStorageBucket.bucketName }},
              endpoint: {{ .Values.prometheusThanosStorageBucket.endpoint }},
              insecure: false,
              signature_version2: false,
              sse_config: {
                type: SSE-KMS,
                kms_key_id: {{ .Values.prometheusThanosStorageBucket.kmsKeyId }}
              }
            } 
          }"
          - "--log.level=debug"